#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-xstream
Version  : 1.4.11.1
Release  : 5
URL      : https://github.com/x-stream/xstream/archive/XSTREAM_1_4_11_1.tar.gz
Source0  : https://github.com/x-stream/xstream/archive/XSTREAM_1_4_11_1.tar.gz
Source1  : https://repo1.maven.org/maven2/com/thoughtworks/xstream/xstream-parent/1.4.10/xstream-parent-1.4.10.pom
Source2  : https://repo1.maven.org/maven2/com/thoughtworks/xstream/xstream-parent/1.4.11.1/xstream-parent-1.4.11.1.pom
Source3  : https://repo1.maven.org/maven2/com/thoughtworks/xstream/xstream-parent/1.4.9/xstream-parent-1.4.9.pom
Source4  : https://repo1.maven.org/maven2/com/thoughtworks/xstream/xstream/1.4.10/xstream-1.4.10.jar
Source5  : https://repo1.maven.org/maven2/com/thoughtworks/xstream/xstream/1.4.10/xstream-1.4.10.pom
Source6  : https://repo1.maven.org/maven2/com/thoughtworks/xstream/xstream/1.4.11.1/xstream-1.4.11.1.jar
Source7  : https://repo1.maven.org/maven2/com/thoughtworks/xstream/xstream/1.4.11.1/xstream-1.4.11.1.pom
Source8  : https://repo1.maven.org/maven2/com/thoughtworks/xstream/xstream/1.4.9/xstream-1.4.9.jar
Source9  : https://repo1.maven.org/maven2/com/thoughtworks/xstream/xstream/1.4.9/xstream-1.4.9.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause
Requires: mvn-xstream-data = %{version}-%{release}
Requires: mvn-xstream-license = %{version}-%{release}
BuildRequires : apache-maven
BuildRequires : buildreq-mvn

%description
***********
********************** XStream **********************
***********
"Java to XML Serialization, and back again"

%package data
Summary: data components for the mvn-xstream package.
Group: Data

%description data
data components for the mvn-xstream package.


%package license
Summary: license components for the mvn-xstream package.
Group: Default

%description license
license components for the mvn-xstream package.


%prep
%setup -q -n xstream-XSTREAM_1_4_11_1

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-xstream
cp LICENSE.txt %{buildroot}/usr/share/package-licenses/mvn-xstream/LICENSE.txt
cp xstream-distribution/src/content/license.html %{buildroot}/usr/share/package-licenses/mvn-xstream/xstream-distribution_src_content_license.html
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/thoughtworks/xstream/xstream-parent/1.4.10
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/thoughtworks/xstream/xstream-parent/1.4.10/xstream-parent-1.4.10.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/thoughtworks/xstream/xstream-parent/1.4.11.1
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/com/thoughtworks/xstream/xstream-parent/1.4.11.1/xstream-parent-1.4.11.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/thoughtworks/xstream/xstream-parent/1.4.9
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/com/thoughtworks/xstream/xstream-parent/1.4.9/xstream-parent-1.4.9.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/thoughtworks/xstream/xstream/1.4.10
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/com/thoughtworks/xstream/xstream/1.4.10/xstream-1.4.10.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/thoughtworks/xstream/xstream/1.4.10
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/com/thoughtworks/xstream/xstream/1.4.10/xstream-1.4.10.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/thoughtworks/xstream/xstream/1.4.11.1
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/com/thoughtworks/xstream/xstream/1.4.11.1/xstream-1.4.11.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/thoughtworks/xstream/xstream/1.4.11.1
cp %{SOURCE7} %{buildroot}/usr/share/java/.m2/repository/com/thoughtworks/xstream/xstream/1.4.11.1/xstream-1.4.11.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/thoughtworks/xstream/xstream/1.4.9
cp %{SOURCE8} %{buildroot}/usr/share/java/.m2/repository/com/thoughtworks/xstream/xstream/1.4.9/xstream-1.4.9.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/thoughtworks/xstream/xstream/1.4.9
cp %{SOURCE9} %{buildroot}/usr/share/java/.m2/repository/com/thoughtworks/xstream/xstream/1.4.9/xstream-1.4.9.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/thoughtworks/xstream/xstream-parent/1.4.10/xstream-parent-1.4.10.pom
/usr/share/java/.m2/repository/com/thoughtworks/xstream/xstream-parent/1.4.11.1/xstream-parent-1.4.11.1.pom
/usr/share/java/.m2/repository/com/thoughtworks/xstream/xstream-parent/1.4.9/xstream-parent-1.4.9.pom
/usr/share/java/.m2/repository/com/thoughtworks/xstream/xstream/1.4.10/xstream-1.4.10.jar
/usr/share/java/.m2/repository/com/thoughtworks/xstream/xstream/1.4.10/xstream-1.4.10.pom
/usr/share/java/.m2/repository/com/thoughtworks/xstream/xstream/1.4.11.1/xstream-1.4.11.1.jar
/usr/share/java/.m2/repository/com/thoughtworks/xstream/xstream/1.4.11.1/xstream-1.4.11.1.pom
/usr/share/java/.m2/repository/com/thoughtworks/xstream/xstream/1.4.9/xstream-1.4.9.jar
/usr/share/java/.m2/repository/com/thoughtworks/xstream/xstream/1.4.9/xstream-1.4.9.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-xstream/LICENSE.txt
/usr/share/package-licenses/mvn-xstream/xstream-distribution_src_content_license.html
