#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-xstream
Version  : 1.4.11.1
Release  : 2
URL      : https://github.com/x-stream/xstream/archive/XSTREAM_1_4_11_1.tar.gz
Source0  : https://github.com/x-stream/xstream/archive/XSTREAM_1_4_11_1.tar.gz
Source1  : https://repo1.maven.org/maven2/com/thoughtworks/xstream/xstream-parent/1.4.11.1/xstream-parent-1.4.11.1.pom
Source2  : https://repo1.maven.org/maven2/com/thoughtworks/xstream/xstream-parent/1.4.9/xstream-parent-1.4.9.pom
Source3  : https://repo1.maven.org/maven2/com/thoughtworks/xstream/xstream/1.4.11.1/xstream-1.4.11.1.jar
Source4  : https://repo1.maven.org/maven2/com/thoughtworks/xstream/xstream/1.4.11.1/xstream-1.4.11.1.pom
Source5  : https://repo1.maven.org/maven2/com/thoughtworks/xstream/xstream/1.4.9/xstream-1.4.9.jar
Source6  : https://repo1.maven.org/maven2/com/thoughtworks/xstream/xstream/1.4.9/xstream-1.4.9.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause
Requires: mvn-xstream-data = %{version}-%{release}

%description
***********
********************** XStream **********************
***********
"Java to XML Serialization, and back again"

%package data
Summary: data components for the mvn-xstream package.
Group: Data

%description data
data components for the mvn-xstream package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/thoughtworks/xstream/xstream-parent/1.4.11.1
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/thoughtworks/xstream/xstream-parent/1.4.11.1/xstream-parent-1.4.11.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/thoughtworks/xstream/xstream-parent/1.4.9
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/com/thoughtworks/xstream/xstream-parent/1.4.9/xstream-parent-1.4.9.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/thoughtworks/xstream/xstream/1.4.11.1
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/com/thoughtworks/xstream/xstream/1.4.11.1/xstream-1.4.11.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/thoughtworks/xstream/xstream/1.4.11.1
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/com/thoughtworks/xstream/xstream/1.4.11.1/xstream-1.4.11.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/thoughtworks/xstream/xstream/1.4.9
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/com/thoughtworks/xstream/xstream/1.4.9/xstream-1.4.9.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/thoughtworks/xstream/xstream/1.4.9
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/com/thoughtworks/xstream/xstream/1.4.9/xstream-1.4.9.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/thoughtworks/xstream/xstream-parent/1.4.11.1/xstream-parent-1.4.11.1.pom
/usr/share/java/.m2/repository/com/thoughtworks/xstream/xstream-parent/1.4.9/xstream-parent-1.4.9.pom
/usr/share/java/.m2/repository/com/thoughtworks/xstream/xstream/1.4.11.1/xstream-1.4.11.1.jar
/usr/share/java/.m2/repository/com/thoughtworks/xstream/xstream/1.4.11.1/xstream-1.4.11.1.pom
/usr/share/java/.m2/repository/com/thoughtworks/xstream/xstream/1.4.9/xstream-1.4.9.jar
/usr/share/java/.m2/repository/com/thoughtworks/xstream/xstream/1.4.9/xstream-1.4.9.pom
